## 아래 가이드에 따라서 고객 구매데이터를 생성하고 아래사항을 수행하세요(관측치 10000개)

#### Q1. 고객 속성(id, 성별, 연령, 거주지역) 데이터와 거래 데이터를 통합한 데이터 프레임 df를 생성하세요.

거래 건수
- id : 1 ~ 10000번 일련번호

고객별 속성 데이터
- cusno : 고객 번호(1000) 
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성

거래 데이터
- day : 요일
- date : 2020-01-01 ~ 2021-12-31 사이의 날짜 생성 후 거래 년도에 해당하는 날짜를 랜덤하게 적용
- product_19 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10 ~ 30
- product_20 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10 ~ 30
- price_19 : 1000 ~ 50000 사이 실수 난수 생성
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_19 : 1 ~ 100 사이 정수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- time_19 : 01 ~ 24 사이 정수 난수 생성
- time_20 : 01 ~ 24 사이 정수 난수 생성
- amount_19 : price_19 * quantity_19
- amount_20 : price_20 * quantity_20
- sales : 19년 대비 20년구매금액이 증가면 1, 감소면 0

#### Q2. df를 수정하여 5가지 이상의 인사이트를 포함한 데이터 셋으로 변환하세요

#### Q3. df 를 탐색적 분석을 통하여 인사이트를 도출하세요.

In [1]:
import warnings
warnings.filterwarnings('ignore')
import random
import numpy as np
import pandas as pd
import time
import datetime
from datetime import datetime
# def price_20():
#     if df.product_20 >= 10 and df.product_20 < 20:
#         df.price_20 = np.random.randint(10,500,size = 1000)*100
#         return df.price_20
#     if df.product_20 >= 20 and df.product_20 < 30:
#         df.price_20 = np.random.randint(10,500,size = 1000)*100
#         return df.price_20
#     else:
#         df.price_20 = np.random.randint(10,500,size = 1000)*100
#         return df.price_20
    
# def price_21:
#     if df.price_21 >= 1000 and df.price_21 <= 10000:
#         df.product_21 = 10
#         return df.product_21
#     elif df.price_21 >= 40000 and df.price_21 <= 50000:
#         df.product_21 = 30
#         return df.product_21
#     else:
#         df.product_21 = 20
#         return df.product_21

ar = np.zeros((10000,18))
# ar = np.zeros((10000,15))
columns = ['id1','cusno','gender','age','region','day','date_20','date_21',
#            'date_year',
           'product_20',
           'product_21',
           'price_20',
           'price_21',
           'quantity_20',
           'quantity_21',
#            'time',
           'time','amount_20',
           'amount_21',
           'sales']
# columns = ['id1','cusno','gender','age','region','day','date','product','price','quantity','time_20',
#            'time_21','amount_20','amount_21','sales']
index = [np.arange(10000)]
df = pd.DataFrame(ar,index,columns = columns)

np.random.seed(0)
df.id1 = np.arange(1,10001) # 고객 번호

cusnos = np.random.randint(1,1001,size=10000) # 고객 1000명
df.cusno = cusnos

genders = np.random.randint(2,size=10000) 
ages = np.random.randint(1,81,size=10000)
regions = np.random.randint(1,10,size=10000) 



gendercus = []
agecus = []
regioncus = []
for i in range(10000):
    gendercus.append(genders[cusnos[i]-1])
    agecus.append(ages[cusnos[i]-1])
    regioncus.append(regions[cusnos[i]-1])
    
df.gender = gendercus
df.age = agecus
df.region = regioncus

df.day = np.random.choice(['월','화','수','목','금','토','일'],size=10000)
a = np.arange('2020-01-01','2020-12-31',dtype='datetime64[D]')
b = np.arange('2021-01-01','2021-12-31',dtype='datetime64[D]')
df.date_20 = np.random.choice(a,size=10000)
df.date_21 = np.random.choice(b,size=10000)
# df.date_year = np.where(df['date'].dt.year == 2020,2020,2021)
# dataf = pd.concat([df.date_year],axis=1) # df.date_year 시리즈를 데이터프레임으로 변경

price20 = np.random.randint(10,500,size=(10000,))*100
price21 = np.random.randint(10,500,size=(10000,))*100
df.price_20 = price20
df.price_21 = price21

bin_names = ['10(저가)','30(중가)','50(고가)']
# 1000~10000 10000~20000 20000~30000 30000~40000 40000~50000
count,bin_dividers = np.histogram(df.price_20,bins=3)                
df['product_20'] = pd.cut(x=df.price_20,
                   bins=bin_dividers,
                   labels=bin_names, 
                   include_lowest=True)

count,bin_dividers = np.histogram(df.price_21,bins=3)                
df['product_21'] = pd.cut(x=df.price_21,
                   bins=bin_dividers,
                   labels=bin_names, 
                   include_lowest=True)

# a = np.random.randint(10,30,size = 10000)
# for i in range(1,10000):
#     df.product_20 = np.where(dataf == 2020, a[i],0) # 자꾸 12만 나옴
# df.product_21 = np.where(dataf == 2021, np.random.randint(10,30,size = 10000),0)

# pricearray= np.random.randint(10,500,size = 1000)*100
# for i in range(1,1001):    
#     df.price_20 = pricearray[df.product_20[i]]
#     df.price_21 = pricearray[df.product_21[i]]


# product_20 = df[df.date.dt.year == 2020]
# print(df.date[df['date'] == 2020])
# df.date_20 = df.loc[df['date']=='2020',]
# print(df.loc[df['date']].dt.year)

# df.product_20 = (df['date'].dt.year.where(df['date'].dt.year == 2020, 2020,2021)).astype(int)

# print(df.date.dt.year,type(df.date.dt.year))
# print(df['date'],type(df['date']))

# 날짜가 20년도면 물건도 20년 가격도 20년
# a1 = df.date.iloc[:,0] 
# df.loc[df['date'].dt.year < 2021,['date']]
# if df.date_year == 2020 :
#     df.product = np.random.randint(10,30,size = 10000)
# elif b > 2020:
#     df.product_20 = 0
# elif b <= 2021:
# df.product_21 = np.random.randint(10,30,size = 10000)
# elif b > 2021:
#     df.product_21 = 0
# print(df.date.dt.year)
# df.date['Year'].dt.year
# print(type(df.date.dt.year))

# pricearray= np.random.randint(10,500,size = 1000)*100
# for i in range(1,1001):    
#     df.price_20 = pricearray[df.product_20[i]]
#     df.price_21 = pricearray[df.product_21[i]]


# df.quantity_20 = np.random.randint(1,100,size=10000)

df.quantity_20 = np.random.randint(1,100,size=10000)
df.quantity_21 = np.random.randint(1,100,size=10000)
# df.time_20 = np.random.randint(1,25,size=10000)
df.time = np.random.randint(1,25,size=10000)
df.amount_20 = df.price_20 * df.quantity_20
df.amount_21= df.price_21 * df.quantity_21
df.sales = np.where(df.amount_20 < df.amount_21, 1,0) 
# 만약에 중복된 cusno가 20.21년 둘다 구매했을경우 감소 하면 0 증가하면 1을 sales로 구현
print(df.shape)
df.head(20)

(10000, 18)

,id1,cusno,gender,age,region,day,date_20,date_21,product_20,product_21,price_20,price_21,quantity_20,quantity_21,time,amount_20,amount_21,sales
0,1,685,1,33,6,금,2020-08-16,2021-08-16,30(중가),10(저가),32500,11700,27,2,24,877500,23400,0
1,2,560,1,65,7,월,2020-06-27,2021-11-23,10(저가),50(고가),15700,35800,26,6,8,408200,214800,0
2,3,630,1,41,7,토,2020-05-21,2021-03-08,10(저가),30(중가),14500,18300,75,8,20,1087500,146400,0
3,4,193,1,27,9,목,2020-09-19,2021-12-08,30(중가),10(저가),27700,9600,32,28,5,886400,268800,0
4,5,836,0,1,8,월,2020-07-18,2021-09-17,10(저가),10(저가),1000,9000,8,78,7,8000,702000,1
5,6,764,1,28,9,일,2020-08-01,2021-05-17,30(중가),50(고가),25700,49200,16,72,12,411200,3542400,1
6,7,708,1,5,2,수,2020-09-24,2021-04-27,30(중가),50(고가),31000,41700,64,36,11,1984000,1501200,0
7,8,360,0,10,8,토,2020-10-11,2021-06-23,50(고가),50(고가),47700,46900,2,23,6,95400,1078700,1
8,9,10,1,23,4,토,2020-10-26,2021-10-19,50(고가),50(고가),35500,40500,18,70,5,639000,2835000,1
9,10,724,1,49,7,수,2020-06-25,2021-10-04,50(고가),30(중가),48900,17700,75,75,5,3667500,1327500,0
10,11,278,1,45,1,금,2020-03-19,2021-11-15,50(고가),50(고가),49100,40900,40,30,16,1964000,1227000,0
11,12,755,1,20,9,토,2020-01-08,2021-09-05,30(중가),50(고가),27100,37500,12,87,21,325200,3262500,1
12,13,805,0,65,1,월,2020-04-08,2021-10-02,30(중가),50(고가),24400,39300,16,22,12,390400,864600,1
13,14,600,1,49,6,화,2020-11-20,2021-08-04,30(중가),30(중가),18900,19000,3,59,18,56700,1121000,1
14,15,71,1,24,8,토,2020-05-22,2021-03-22,30(중가),30(중가),27000,31000,75,69,1,2025000,2139000,1
15,16,473,0,30,9,목,2020-06-03,2021-01-29,50(고가),50(고가),36100,35400,32,73,17,1155200,2584200,1
16,17,601,1,71,5,월,2020-01-01,2021-02-06,30(중가),30(중가),33100,20200,80,91,22,2648000,1838200,0
17,18,397,0,49,2,화,2020-08-30,2021-05-27,30(중가),30(중가),17500,18800,42,69,7,735000,1297200,1
18,19,315,1,59,2,일,2020-05-09,2021-08-16,50(고가),30(중가),44700,23300,80,5,20,3576000,116500,0
19,20,706,1,39,1,일,2020-02-18,2021-11-25,10(저가),30(중가),10300,23200,22,15,5,226600,348000,1

In [ ]:
스포츠 용품 
if
20년도 롤드컵 담원기아의 우승으로인한 굿즈 판매량의 증가 
20년~21년까지 SKT 물품은 꾸준하게 팔리고 있음
# 10월31일 이후 pc방의자 고가,유니폼 중가,장패드 저가
# 20년도 마스크 사재기로인한 제품 판매량의 증가
21년도 8월 올림픽 야구대표팀과 야구관계자들의 부정과 NC소프트 주가폭락이 겹치면서 20년도에는 많은
물품을 샀는데 21년도에는 물품을 산 양이 줄어든 사람이 있을거임. 혹은 21년도 7월까지는 많이샀지만
8월이후부터 급락하거나
123

      cusno
0       685
1       560
2       630
3       193
4       836
...     ...
9995    989
9996     81
9997    276
9998    677
9999    272

[10000 rows x 1 columns]