In [1]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 1.4 MB/s
Installing collected packages: pymysql
Successfully installed pymysql-1.0.2

In [2]:
import pandas as pd
import pymysql
conn = pymysql.connect(host='34.64.224.44', user='root', password='A412GBVSDsawe%$we', db='smart_factory')
sql_state='SELECT * FROM `production_planning`'
planning=pd.read_sql_query(sql_state, conn)

sql_state='SELECT * FROM `recipe`'
recipe=pd.read_sql_query(sql_state, conn)

In [3]:
planning=planning.groupby(['SOLDDATE','PRODNAME']).sum().reset_index()

In [4]:
daily_raw=pd.merge(planning,recipe,how='left',on=['PRODNAME'])

In [5]:
daily_raw.columns

Index(['SOLDDATE', 'PRODNAME', 'CUSTID', 'YEAR', 'MONTH', 'SR11002', 'SR35218',
       'SR35904', 'SR15500', 'SR13801', 'SR16600', 'SR35224', 'SR35903',
       'SR68222', 'SR35225', 'SR35228', 'SR38117', 'SR16002', 'SR35758',
       'SR35210', 'SR34364', 'SR35500', 'SR35556', 'SR18520', 'SR35217',
       'SR35905', 'SR35755', 'SR34307', 'SR35760', 'SR35761', 'SR35765',
       'SR34311', 'SR35211', 'TSN4012039104', 'SR35221', 'SR16003',
       'PEMA023017400', 'TSN4012057700', 'SR47093', 'SSA043031400'],
      dtype='object')

In [7]:
for raw in ['SR11002', 'SR35218','SR35904', 'SR15500', 'SR13801', 'SR16600', 'SR35224', 'SR35903',
       'SR68222', 'SR35225', 'SR35228', 'SR38117', 'SR16002', 'SR35758',
       'SR35210', 'SR34364', 'SR35500', 'SR35556', 'SR18520', 'SR35217',
       'SR35905', 'SR35755', 'SR34307', 'SR35760', 'SR35761', 'SR35765',
       'SR34311', 'SR35211', 'TSN4012039104', 'SR35221', 'SR16003',
       'PEMA023017400', 'TSN4012057700', 'SR47093', 'SSA043031400']:
  daily_raw[raw] = daily_raw[raw]*daily_raw['QUANT']

SyntaxError: ignored

In [ ]:
daily_raw=daily_raw.drop(['PRODNAME','QUANT'],axis=1)

In [ ]:
daily_raw=daily_raw.groupby('SOLDDATE').sum()

In [ ]:
daily_raw=daily_raw.reset_index()

In [ ]:
daily_raw

,SOLDDATE,SR11002,SR35218,SR35904,SR15500,SR13801,SR16600,SR35224,SR35903,SR68222,...,SR35765,SR34311,SR35211,TSN4012039104,SR35221,SR16003,PEMA023017400,TSN4012057700,SR47093,SSA043031400
0,2022-01-01,72289.188333,17307.098446,7394.444148,1037.292559,229.651911,2717.320464,10844.957691,2659.730014,93.473643,...,0.000000,42.926169,1124.174076,0.000000,1127.761701,41.404310,23.625000,0.000000,0.0,9.753571
1,2022-01-02,83719.536066,5044.633645,7396.948794,968.999679,194.223231,2863.597177,12025.857313,2566.156173,106.675644,...,0.000000,47.221104,1467.851185,48.200000,978.879658,50.415719,23.625000,57.000000,0.0,9.727455
2,2022-01-03,51599.154562,19096.392679,4975.614859,2.576357,158.920675,2750.741021,7601.318276,2014.103029,80.090574,...,0.000000,22.038230,612.556561,0.000000,306.665982,29.895013,23.625000,0.000000,0.0,9.196429
3,2022-01-04,73789.556968,17368.148465,6659.487754,1036.692751,195.093321,3309.961192,9338.966395,2611.243468,105.568886,...,0.000000,39.100082,720.015724,0.000000,1059.335716,40.930215,31.500000,0.000000,0.0,12.586905
4,2022-01-05,90764.461099,11906.019999,8619.931949,5.807830,241.932730,5056.738738,13350.114869,3403.549890,123.171272,...,0.000000,49.438163,1451.828788,48.200000,681.181139,51.325214,31.500000,57.000000,0.0,12.726190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,2022-03-26,50037.901240,1534.614362,5589.782359,6.346242,121.961143,1851.982166,7532.521233,2064.572119,66.754033,...,0.000000,33.692465,725.629284,61.971429,412.005491,30.823932,23.041667,73.285714,0.0,9.578516
81,2022-03-28,132105.931482,18909.067913,11403.962797,9.182141,303.398625,3925.408854,16109.830879,5248.890152,171.454526,...,0.000000,62.099052,1374.901188,0.000000,1020.108465,72.781608,54.687500,0.000000,0.0,21.736194
82,2022-03-29,188599.578115,60145.984581,19578.862948,7170.431309,586.982304,7148.334508,28647.089299,6761.922613,239.355002,...,0.000000,93.863934,2606.281918,0.000000,2252.947417,113.329259,98.437500,0.000000,0.0,38.507068
83,2022-03-30,148929.249070,41646.802851,16589.112694,1800.923058,448.705024,5862.518878,24040.873816,5863.762719,202.527834,...,0.000000,114.120154,2504.266419,61.971429,2344.748364,83.534266,46.083333,73.285714,0.0,19.801229
84,2022-03-31,206401.113721,18328.346150,17834.420973,1801.997643,481.747387,7750.359510,26979.879624,6765.488483,267.266188,...,153.974338,115.310928,2828.379276,61.110714,2432.439660,119.567050,76.562500,72.267857,0.0,30.636698

In [ ]:
from sqlalchemy import create_engine

db_connection_str = 'mysql+pymysql://root:A412GBVSDsawe%$we@34.64.224.44:3306/smart_factory'
db_connection = create_engine(db_connection_str)
conn = db_connection.connect()

# df_per_sql.to_sql(name = 'building_permission',con = db_connection, index = False)
daily_raw.to_sql(name = 'daily_raw',con = db_connection, index = False, if_exists = 'replace') # 테이블 삭제하고 새로 만들 때 사용
# df_per_sql.to_sql(name = 'building_permission',con = db_connection, index = False, if_exists = 'append') # 데이터를 추가할 때 사용

In [ ]:
# 이전 5년 데이터에서

In [ ]:
import pandas as pd
import pymysql
conn = pymysql.connect(host='34.64.224.44', user='root', password='A412GBVSDsawe%$we', db='smart_factory')
sql_state='SELECT * FROM `rawdata`'
planning=pd.read_sql_query(sql_state, conn)

sql_state='SELECT * FROM `recipe`'
recipe=pd.read_sql_query(sql_state, conn)

In [ ]:
planning=planning.groupby(['SOLDDATE','PRODNAME']).sum().reset_index()

In [ ]:
planning

,SOLDDATE,PRODNAME,TEMP_M,HUM_M,CONSTRUCTION,CONSTRUCTION_RATE,QUANT
0,2017-01-01,CSA4000,0.005189,0.199493,0.216297,0.112057,5000.0
1,2017-01-01,CSA5000,0.020756,0.797972,0.865186,0.448227,24800.0
2,2017-01-01,PEMA-HR1000,0.057079,2.194424,2.379262,1.232624,67100.0
3,2017-01-01,PEMA-HR1500,0.020756,0.797972,0.865186,0.448227,22400.0
4,2017-01-01,PEMA-PCM2000B,0.005189,0.199493,0.216297,0.112057,3100.0
...,...,...,...,...,...,...,...
17879,2021-12-31,PEMA-PR1000,0.721757,1.317000,3.000000,1.527660,38800.0
17880,2021-12-31,PEMA-SN400,0.173640,0.351000,1.000000,0.509220,11600.0
17881,2021-12-31,PEMA-SR2000,0.761506,0.973000,3.000000,1.527660,20000.0
17882,2021-12-31,PEMA-SR2000A,0.215481,0.356000,1.000000,0.509220,7500.0
17883,2021-12-31,PEMA-SR3000F,0.215481,0.356000,1.000000,0.509220,5200.0

In [ ]:
daily_raw=pd.merge(planning,recipe,how='left',on=['PRODNAME'])

In [ ]:
for raw in ['SR11002', 'SR35218','SR35904', 'SR15500', 'SR13801', 'SR16600', 'SR35224', 'SR35903',
       'SR68222', 'SR35225', 'SR35228', 'SR38117', 'SR16002', 'SR35758',
       'SR35210', 'SR34364', 'SR35500', 'SR35556', 'SR18520', 'SR35217',
       'SR35905', 'SR35755', 'SR34307', 'SR35760', 'SR35761', 'SR35765',
       'SR34311', 'SR35211', 'TSN4012039104', 'SR35221', 'SR16003',
       'PEMA023017400', 'TSN4012057700', 'SR47093', 'SSA043031400']:
  daily_raw[raw] = daily_raw[raw]*daily_raw['QUANT']

In [ ]:
daily_raw=daily_raw.drop(['PRODNAME','QUANT'],axis=1)
daily_raw=daily_raw.groupby('SOLDDATE').sum()
daily_raw=daily_raw.reset_index()

In [ ]:
daily_raw=daily_raw.drop(['TEMP_M','HUM_M','CONSTRUCTION','CONSTRUCTION_RATE'],axis=1)

In [ ]:
daily_raw

,SOLDDATE,SR11002,SR35218,SR35904,SR15500,SR13801,SR16600,SR35224,SR35903,SR68222,...,SR35765,SR34311,SR35211,TSN4012039104,SR35221,SR16003,PEMA023017400,TSN4012057700,SR47093,SSA043031400
0,2017-01-01,101644.178790,4077.538360,10399.078694,8.909897,281.036228,3908.170534,15608.997965,4031.455644,138.302097,...,0.0,63.830236,1650.108149,57.667857,839.673868,60.370722,36.166667,68.196429,0.0,14.959444
1,2017-01-02,123878.992493,21599.820256,13073.285634,9.719737,334.388973,4547.968173,17869.069056,4568.584617,162.916583,...,0.0,75.891960,1733.533979,57.667857,1103.810431,76.854171,63.291667,68.196429,0.0,25.072721
2,2017-01-03,128818.380787,14510.823876,12724.435274,9.302890,322.105058,4641.430462,19383.809995,4336.397683,170.433461,...,0.0,92.825355,2307.835141,57.667857,1230.773412,74.729985,36.166667,68.196429,0.0,15.313462
3,2017-01-04,135204.938539,40780.853591,11719.968156,2488.174178,332.728100,4647.389686,17684.905452,4959.015963,153.638567,...,0.0,70.043544,1515.298608,57.667857,2035.304064,74.082814,36.166667,68.196429,0.0,15.490471
4,2017-01-05,68308.731548,43241.598828,8022.728134,7.744355,261.332074,2546.364760,11606.665108,2813.598323,91.558609,...,0.0,53.352900,937.912829,57.667857,1248.102873,37.530916,9.041667,68.196429,0.0,5.200185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1813,2021-12-27,181472.306223,61034.807382,13326.045085,9780.621778,440.399436,4988.027877,19764.851321,4655.896670,161.487462,...,0.0,81.238732,1876.948474,154.928571,2962.669620,97.427987,47.979167,183.214286,0.0,19.949399
1814,2021-12-28,242135.216200,60849.205601,23022.660666,9308.492825,633.284115,8317.423168,36106.082970,8421.585638,278.815734,...,0.0,145.190237,4404.993951,202.267857,3777.099225,132.789079,47.979167,239.196429,0.0,22.180872
1815,2021-12-29,220894.336694,54367.403731,21735.867970,16186.480339,599.241251,8385.450188,34047.497336,7636.004438,266.165791,...,0.0,120.637918,3802.249614,0.000000,2972.591197,127.772054,72.479167,0.000000,0.0,29.640553
1816,2021-12-30,149448.558529,23036.982234,15015.411949,11573.131968,363.166126,5756.732167,22665.014512,5076.868242,208.991163,...,0.0,105.991930,2779.046782,0.000000,1922.926329,97.069613,46.666667,0.000000,0.0,19.677400
1817,2021-12-31,183483.797833,26993.094562,15591.730292,11.175377,474.617218,6040.174753,24490.309112,5858.361768,213.536349,...,0.0,104.515813,2984.860891,99.842857,3605.310197,104.675214,44.187500,118.071429,0.0,18.663550

In [ ]:
from sqlalchemy import create_engine

db_connection_str = 'mysql+pymysql://root:A412GBVSDsawe%$we@34.64.224.44:3306/smart_factory'
db_connection = create_engine(db_connection_str)
conn = db_connection.connect()

# df_per_sql.to_sql(name = 'building_permission',con = db_connection, index = False)
daily_raw.to_sql(name = 'past_daily_raw',con = db_connection, index = False, if_exists = 'replace') # 테이블 삭제하고 새로 만들 때 사용
# df_per_sql.to_sql(name = 'building_permission',con = db_connection, index = False, if_exists = 'append') # 데이터를 추가할 때 사용