In [181]:
import requests
import re
import urllib
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import datetime
from dateutil.relativedelta import relativedelta
import time
# import selenium
# from selenium import webdriver
# from selenium.webdriver.common.keys import Keys
from sqlalchemy import create_engine
import warnings
warnings.filterwarnings('ignore')

# # 건축허가면적
---

## # 인터넷에서 데이터 불러오기
---

### # 월별 데이터
---

#### # beautifulsoup 사용
---

In [183]:
start = 200201 # 검색 시작 날짜

year = datetime.date.today().year
month = (datetime.date.today() + relativedelta(months = -2)).month

end = str(year) + str(month).zfill(2) # 검색 마지막 날짜

url = f'http://www.index.go.kr/strata/jsp/showStblGams3.jsp?stts_cd=122401&idx_cd=1224&freq=M&period={start}:{end}'

res = urllib.request.urlopen(url)
html = res.read().decode('utf-8')
soup = BeautifulSoup(html, 'html.parser')
months = soup.find_all(class_ = 'tc')

columns = []
for i in months:
    month = i.text[:4] + ' ' + i.text[4:]
    columns.append(month)

index = ['총계', '전월대비증감율', '주거용', '상업용', '농수산용', '공업용', '공공용', '교육사회용', '기타']

df_per = pd.DataFrame(index = index, columns = columns)

data_len = (int(str(end)[:4]) - int(str(start)[:4])) * 12 + int(str(end)[4:]) - int(str(start)[4:]) + 1

for i, j in enumerate(index):
    datas = soup.find_all(id = f'tr_122401_{i+1}')
    for data in datas:
        figures = re.sub(',', '', data.text).split('\n')
        df_per.loc[j] = figures[2:len(figures)-1]

df_per

,2002 01월,2002 02월,2002 03월,2002 04월,2002 05월,2002 06월,2002 07월,2002 08월,2002 09월,2002 10월,...,2021 05월,2021 06월,2021 07월,2021 08월,2021 09월,2021 10월,2021 11월,2021 12월,2022 01월,2022 02월
총계,9344374,8294507,13960644,13486345,14590626,10258984,11420476,9765357,10220654,12973744,...,13891755,16013705,14591577,13946424,14652194,14689855,14483042,19169150,13736304,11862344
전월대비증감율,-,-12.7,40.6,-3.5,7.6,-42.2,10.2,-16.9,4.5,-,...,-14.0,-19.5,-8.9,-4.4,5.1,0.3,-1.4,32.4,-28.3,-13.6
주거용,3788023,3466368,6329311,5315253,5213790,4155528,3991677,3786017,4280573,5679410,...,4399673,5457687,5097761,4814965,4909887,5167976,4793022,5830884,5027420,3341809
상업용,3441822,2899801,5068121,5223113,6006266,3519756,4707096,3372034,3648882,4593972,...,3674940,4837628,4295101,3520713,3388875,3863066,4460134,5691514,3328383,3106917
농수산용,207811,172183,246638,301994,329304,264974,268652,296557,242834,324042,...,569891,649438,557002,492156,406101,399821,477336,464124,349763,287273
공업용,1246418,1003784,1257046,1607455,1801005,1308992,1200090,1259565,1098361,1089979,...,1476154,1697128,1346290,1288661,1592140,1243991,1378314,1579046,1861404,1412082
공공용,30748,61736,42940,30898,39754,73576,21810,30071,39415,94558,...,180629,174631,56865,102177,163783,101531,136506,67882,10173,46456
교육사회용,438431,493217,627706,628208,738477,688188,748883,570402,551309,664260,...,897293,979011,811944,845225,973380,966562,879114,1263720,767553,899657
기타,191121,197418,388882,379424,462030,247970,482268,450711,359280,527523,...,2693175,2218182,2426614,2882527,3218028,2946908,2358616,4271980,2391608,2768150

In [ ]:
start = 202103 # 검색 시작 날짜
end = 202203 # 검색 마지막 날짜
path = 'D:\workspace\python\selenium_tool\chromedriver.exe' # 셀레니움 크롬드라이버 파일 위치

url = f'http://www.index.go.kr/strata/jsp/showStblGams3.jsp?stts_cd=122401&idx_cd=1224&freq=M&period={start}:{end}'
driver = webdriver.Chrome(path)
driver.get(url)

months = driver.find_element_by_xpath('//*[@id="trHeader122401_1"]').text.split(' ')

index = ['총계', '전월대비증감율', '주거용', '상업용', '농수산용', '공업용', '공공용', '교육사회용', '기타']
columns = []
for month in months:
    if len(month) != 0:
        month = re.sub('\n', ' ', month)
        columns.append(month)

df_per = pd.DataFrame(index = index, columns = columns)

data_len = (int(str(end)[:4]) - int(str(start)[:4])) * 12 + int(str(end)[4:]) - int(str(start)[4:]) + 1
for i, j in enumerate(index):
    data = driver.find_element_by_xpath(f'//*[@id="tr_122401_{i+1}"]').text.split(' ')
    
    datas = []
    for i in data:
        i = re.sub(',', '', i)
        datas.append(i)
        
    df_per.loc[j] = datas[-data_len:]

driver.close()

df_per

,2021 03월,2021 04월,2021 05월,2021 06월,2021 07월,2021 08월,2021 09월,2021 10월,2021 11월,2021 12월,2022 01월,2022 02월,2022 03월
총계,15159771,16145048,13891755,16013705,14591577,13946424,14652194,14689855,14483042,19169150,13736304,11862344,15057792
전월대비증감율,39.5,6.5,-14.0,-19.5,-8.9,-4.4,5.1,0.3,-1.4,32.4,-28.3,-13.6,26.9
주거용,5135024,5131413,4399673,5457687,5097761,4814965,4909887,5167976,4793022,5830884,5027420,3341809,5054232
상업용,4084209,5252041,3674940,4837628,4295101,3520713,3388875,3863066,4460134,5691514,3328383,3106917,3923553
농수산용,722085,828137,569891,649438,557002,492156,406101,399821,477336,464124,349763,287273,359828
공업용,1515167,2112013,1476154,1697128,1346290,1288661,1592140,1243991,1378314,1579046,1861404,1412082,1692780
공공용,22231,103698,180629,174631,56865,102177,163783,101531,136506,67882,10173,46456,169533
교육사회용,901519,776179,897293,979011,811944,845225,973380,966562,879114,1263720,767553,899657,677054
기타,2779536,1941567,2693175,2218182,2426614,2882527,3218028,2946908,2358616,4271980,2391608,2768150,3180812

#### # selenium 사용
---
- 사용 안함

In [ ]:
start = 202203 # 검색 시작 날짜
end = 202203 # 검색 마지막 날짜
path = 'D:\workspace\python\selenium_tool\chromedriver.exe' # 셀레니움 크롬드라이버 파일 위치

url = f'http://www.index.go.kr/strata/jsp/showStblGams3.jsp?stts_cd=122401&idx_cd=1224&freq=M&period={start}:{end}'
driver = webdriver.Chrome(path)
driver.get(url)

months = driver.find_element_by_xpath('//*[@id="trHeader122401_1"]').text.split(' ')

index = ['총계', '전월대비증감율', '주거용', '상업용', '농수산용', '공업용', '공공용', '교육사회용', '기타']
columns = []
for month in months:
    if len(month) != 0:
        month = re.sub('\n', ' ', month)
        columns.append(month)

df_per = pd.DataFrame(index = index, columns = columns)

data_len = (int(str(end)[:4]) - int(str(start)[:4])) * 12 + int(str(end)[4:]) - int(str(start)[4:]) + 1
for i, j in enumerate(index):
    data = driver.find_element_by_xpath(f'//*[@id="tr_122401_{i+1}"]').text.split(' ')
    
    datas = []
    for i in data:
        i = re.sub(',', '', i)
        datas.append(i)
        
    df_per.loc[j] = datas[-data_len:]

driver.close()

df_per

         2022 03월
총계       15057792
전월대비증감율      26.9
주거용       5054232
상업용       3923553
농수산용       359828
공업용       1692780
공공용        169533
교육사회용      677054
기타        3180812

#### # MariaDB에 데이터 입력
---

In [ ]:
df_per_sql = df_per.T.reset_index()
df_per_sql['index']
df_per_sql['연도'] = [int(year[:4]) for year in df_per_sql['index']]
df_per_sql['월'] = [int(month[4:7]) for month in df_per_sql['index']]
df_per_sql = df_per_sql[['연도', '월', '총계', '주거용', '상업용', '농수산용', '공업용', '공공용', '교육사회용', '기타']]
df_per_sql.iloc[:, 2:] = df_per_sql.iloc[:, 2:].astype('float64')

display(df_per_sql)

db_connection_str = 'mysql+pymysql://root:A412GBVSDsawe%$we@34.64.224.44:3306/smart_factory'
db_connection = create_engine(db_connection_str)
conn = db_connection.connect()

# df_per_sql.to_sql(name = 'building_permission',con = db_connection, index = False)
# df_per_sql.to_sql(name = 'building_permission',con = db_connection, index = False, if_exists = 'replace') # 테이블 삭제하고 새로 만들 때 사용
df_per_sql.to_sql(name = 'building_permission_temp',con = db_connection, index = False, if_exists = 'append') # 데이터를 추가할 때 사용

,연도,월,총계,주거용,상업용,농수산용,공업용,공공용,교육사회용,기타
0,2022,3,15057792.0,5054232.0,3923553.0,359828.0,1692780.0,169533.0,677054.0,3180812.0

### # 분기별 데이터
---

In [ ]:
start = 201901 # 검색 시작 분기
end = 202104 # 검색 마지막 분기
path = 'D:\workspace\python\selenium_tool\chromedriver.exe' # 셀레니움 크롬드라이버 파일 위치

url = f'http://www.index.go.kr/strata/jsp/showStblGams3.jsp?stts_cd=122401&idx_cd=1224&freq=Q&period={start}:{end}'
driver = webdriver.Chrome(path)
driver.get(url)

months = driver.find_element_by_xpath('//*[@id="trHeader122401_1"]').text.split(' ')

index = ['총계', '전년대비증감율', '주거용', '상업용', '농수산용', '공업용', '공공용', '교육사회용', '기타']
columns = []
for month in months:
    if len(month) != 0:
        month = re.sub('\n', ' ', month)
        columns.append(month)

df_per = pd.DataFrame(index = index, columns = columns)

data_len = (int(str(end)[:4]) - int(str(start)[:4])) * 4 + int(str(end)[4:]) - int(str(start)[4:]) + 1
for i, j in enumerate(index):
    data = driver.find_element_by_xpath(f'//*[@id="tr_122401_{i+1}"]').text.split(' ')
    
    datas = []
    for i in data:
        i = re.sub(',', '', i)
        datas.append(i)
        
    df_per.loc[j] = datas[-data_len:]

driver.close()

df_per

,2019 1/4,2019 2/4,2019 3/4,2019 4/4,2020 1/4,2020 2/4,2020 3/4,2020 4/4,2021 1/4,2021 2/4,2021 3/4,2021 4/4
총계,35007,34259,34021,41004,33229,35628,38312,40138,35622,46050,43190,48342
전년대비증감율,-13.0,-2.1,-0.7,20.5,-19.0,7.2,7.5,4.8,-11.2,29.3,-6.2,11.9
주거용,13057,10224,10133,12826,10174,10533,12215,13137,11972,14988,14822,15791
상업용,8828,9504,8981,10945,9666,9626,11343,10921,10032,13764,11204,14014
농수산용,3237,3718,4662,4297,3078,3007,2473,2203,1855,2047,1455,1341
공업용,3749,4600,4284,3737,4018,4504,3984,4474,3608,5285,4227,4201
공공용,93,180,122,167,151,151,241,365,97,458,322,305
교육사회용,1911,2429,2464,3049,2031,2255,2540,2651,2408,2652,2630,3109
기타,4130,3599,3371,5981,4107,5549,5512,6386,5647,6852,8527,9577

#### # MariaDB에 데이터 입력
---

In [ ]:
df_per_sql = df_per.T.reset_index()
df_per_sql['단위'] = '천m²'
df_per_sql['연도'] = [int(year[:4]) for year in df_per_sql['index']]
df_per_sql['분기'] = [int(month[4:6]) for month in df_per_sql['index']]
df_per_sql = df_per_sql[['연도', '분기', '총계', '전년대비증감율', '주거용', '상업용', '농수산용', '공업용', '공공용', '교육사회용', '기타', '단위']]
df_per_sql.iloc[:, 2:len(df_per_sql.columns)-1] = df_per_sql.iloc[:, 2:len(df_per_sql.columns)-1].astype('float64')

display(df_per_sql)

db_connection_str = 'mysql+pymysql://root:root@127.0.0.1:3306/smart_factory'
db_connection = create_engine(db_connection_str)
conn = db_connection.connect()

# df_per_sql.to_sql(name = 'building_permission',con = db_connection, index = False)
df_per_sql.to_sql(name = 'building_permission',con = db_connection, index = False, if_exists = 'replace') # 테이블 삭제하고 새로 만들 때 사용
# df_per_sql.to_sql(name = 'building_permission',con = db_connection, index = False, if_exists = 'append') # 데이터를 추가할 때 사용

,연도,분기,총계,전년대비증감율,주거용,상업용,농수산용,공업용,공공용,교육사회용,기타,단위
0,2019,1,35007.0,-13.0,13057.0,8828.0,3237.0,3749.0,93.0,1911.0,4130.0,천m²
1,2019,2,34259.0,-2.1,10224.0,9504.0,3718.0,4600.0,180.0,2429.0,3599.0,천m²
2,2019,3,34021.0,-0.7,10133.0,8981.0,4662.0,4284.0,122.0,2464.0,3371.0,천m²
3,2019,4,41004.0,20.5,12826.0,10945.0,4297.0,3737.0,167.0,3049.0,5981.0,천m²
4,2020,1,33229.0,-19.0,10174.0,9666.0,3078.0,4018.0,151.0,2031.0,4107.0,천m²
5,2020,2,35628.0,7.2,10533.0,9626.0,3007.0,4504.0,151.0,2255.0,5549.0,천m²
6,2020,3,38312.0,7.5,12215.0,11343.0,2473.0,3984.0,241.0,2540.0,5512.0,천m²
7,2020,4,40138.0,4.8,13137.0,10921.0,2203.0,4474.0,365.0,2651.0,6386.0,천m²
8,2021,1,35622.0,-11.2,11972.0,10032.0,1855.0,3608.0,97.0,2408.0,5647.0,천m²
9,2021,2,46050.0,29.3,14988.0,13764.0,2047.0,5285.0,458.0,2652.0,6852.0,천m²
10,2021,3,43190.0,-6.2,14822.0,11204.0,1455.0,4227.0,322.0,2630.0,8527.0,천m²
11,2021,4,48342.0,11.9,15791.0,14014.0,1341.0,4201.0,305.0,3109.0,9577.0,천m²

# # 건축착공면적
---

## # 인터넷에서 데이터 불러오기
---

### # 월별로 데이터
---

#### # beautifulsoup 사용
---

In [182]:
start = 200201 # 검색 시작 날짜

year = datetime.date.today().year
month = (datetime.date.today() + relativedelta(months = -2)).month

end = str(year) + str(month).zfill(2) # 검색 마지막 날짜

url = f'http://www.index.go.kr/strata/jsp/showStblGams3.jsp?stts_cd=122402&idx_cd=1224&freq=M&period={start}:{end}'

res = urllib.request.urlopen(url)
html = res.read().decode('utf-8')
soup = BeautifulSoup(html, 'html.parser')
months = soup.find_all(class_ = 'tc')

columns = []
for i in months:
    month = i.text[:4] + ' ' + i.text[4:]
    columns.append(month)

index = ['총계', '전월대비증감율', '주거용', '상업용', '농수산용', '공업용', '공공용', '교육사회용', '기타']

df_const = pd.DataFrame(index = index, columns = columns)

data_len = (int(str(end)[:4]) - int(str(start)[:4])) * 12 + int(str(end)[4:]) - int(str(start)[4:]) + 1

for i, j in enumerate(index):
    datas = soup.find_all(id = f'tr_122402_{i+1}')
    for data in datas:
        figures = re.sub(',', '', data.text).split('\n')
        df_const.loc[j] = figures[2:len(figures)-1]

df_const

,2002 01월,2002 02월,2002 03월,2002 04월,2002 05월,2002 06월,2002 07월,2002 08월,2002 09월,2002 10월,...,2021 05월,2021 06월,2021 07월,2021 08월,2021 09월,2021 10월,2021 11월,2021 12월,2022 01월,2022 02월
총계,4606573,6469007,9791144,7502278,8020439,11471235,8584545,7105475,6368053,8508280,...,12571458,10969332,10615761,9072363,11496673,11721240,11543841,14224754,7309396,7294384
전월대비증감율,-50.4,40.4,51.4,-23.4,6.9,43.0,-25.2,-17.2,-10.4,33.6,...,4.7,-12.7,-3.2,-17.3,26.7,2.0,-1.5,23.2,-48.6,-0.2
주거용,1196476,2126741,4116061,2492311,2980978,5860223,3249995,2659948,2174344,3988907,...,3239832,3675962,3511341,3192223,4348635,4316315,3598611,5457308,1699745,2480321
상업용,1800731,2012309,2873704,2738559,2468974,2851044,3084450,1991695,2077692,1958449,...,4789394,3199932,3151322,2882205,3134789,3006075,3342337,3474508,2422706,1885971
농수산용,105471,148971,253077,299022,552414,278150,195995,172493,245715,204951,...,671651,612984,545319,471486,431308,404530,599388,481155,290212,295254
공업용,988765,853979,1327957,929831,1022873,956574,990873,1446252,913501,915824,...,1326080,1565478,1225227,859425,1163764,1834724,1533741,1242796,1013386,813621
공공용,6810,58895,43854,66600,29459,62385,35710,5605,105940,21280,...,95976,61579,60146,53203,59917,29489,58619,130735,125342,75865
교육사회용,305599,481927,595916,619158,517058,489102,538145,434023,409126,628408,...,985239,599303,658470,475405,401356,643421,630203,1044632,423769,534801
기타,202721,786185,580575,356797,448683,973757,489377,395459,441735,790461,...,1463286,1254094,1463936,1138416,1956904,1486686,1780942,2393620,1334236,1208551

#### # selenium 사용
---

In [ ]:
start = 202203 # 검색 시작 날짜
end = 202203 # 검색 마지막 날짜
path = 'D:\workspace\python\selenium_tool\chromedriver.exe' # 셀레니움 크롬드라이버 파일 위치

url = f'http://www.index.go.kr/strata/jsp/showStblGams3.jsp?stts_cd=122402&idx_cd=1224&freq=M&period={start}:{end}'
driver = webdriver.Chrome(path)
driver.get(url)

months = driver.find_element_by_xpath('//*[@id="trHeader122402_1"]').text.split(' ')

index = ['총계', '전월대비증감율', '주거용', '상업용', '농수산용', '공업용', '공공용', '교육사회용', '기타']
columns = []
for month in months:
    if len(month) != 0:
        month = re.sub('\n', ' ', month)
        columns.append(month)

df_const = pd.DataFrame(index = index, columns = columns)

data_len = (int(str(end)[:4]) - int(str(start)[:4])) * 12 + int(str(end)[4:]) - int(str(start)[4:]) + 1
for i, j in enumerate(index):
    data = driver.find_element_by_xpath(f'//*[@id="tr_122402_{i+1}"]').text.split(' ')
    
    datas = []
    for i in data:
        i = re.sub(',', '', i)
        datas.append(i)
        
    df_const.loc[j] = datas[-data_len:]

driver.close()

df_const.head()

         2022 03월
총계       11636412
전월대비증감율      59.5
주거용       3369687
상업용       3499605
농수산용       438676

#### # MariaDB에 데이터 입력
---

In [ ]:
df_const_sql = df_const.T.reset_index()
df_const_sql['index']
df_const_sql['연도'] = [int(year[:4]) for year in df_const_sql['index']]
df_const_sql['월'] = [int(month[4:7]) for month in df_const_sql['index']]
df_const_sql = df_const_sql[['연도', '월', '총계', '주거용', '상업용', '농수산용', '공업용', '공공용', '교육사회용', '기타']]
df_const_sql.iloc[:, 2:] = df_const_sql.iloc[:, 2:].astype('float64')

display(df_const_sql)

db_connection_str = 'mysql+pymysql://root:A412GBVSDsawe%$we@34.64.224.44:3306/smart_factory'
db_connection = create_engine(db_connection_str)
conn = db_connection.connect()

# df_per_sql.to_sql(name = 'building_permission',con = db_connection, index = False)
# df_const_sql.to_sql(name = 'building_construction',con = db_connection, index = False, if_exists = 'replace') # 테이블 삭제하고 새로 만들 때 사용
df_per_sql.to_sql(name = 'building_construction_temp',con = db_connection, index = False, if_exists = 'append') # 데이터를 추가할 때 사용

,연도,월,총계,주거용,상업용,농수산용,공업용,공공용,교육사회용,기타
0,2022,3,11636412.0,3369687.0,3499605.0,438676.0,1530633.0,221818.0,571069.0,2004924.0

### # 분기별로 불러오기
---

In [ ]:
start = 201901 # 검색 시작 분기
end = 202104 # 검색 마지막 분기

path = 'D:\workspace\python\selenium_tool\chromedriver.exe' # 셀레니움 크롬드라이버 파일 위치

url = f'http://www.index.go.kr/strata/jsp/showStblGams3.jsp?stts_cd=122402&idx_cd=1224&freq=Q&period={start}:{end}'
driver = webdriver.Chrome(path)
driver.get(url)

months = driver.find_element_by_xpath('//*[@id="trHeader122402_1"]').text.split(' ')

index = ['총계', '전년대비증감율', '주거용', '상업용', '농수산용', '공업용', '공공용', '교육사회용', '기타']
columns = []
for month in months:
    if len(month) != 0:
        month = re.sub('\n', ' ', month)
        columns.append(month)

df_const = pd.DataFrame(index = index, columns = columns)

data_len = (int(str(end)[:4]) - int(str(start)[:4])) * 4 + int(str(end)[4:]) - int(str(start)[4:]) + 1
for i, j in enumerate(index):
    data = driver.find_element_by_xpath(f'//*[@id="tr_122402_{i+1}"]').text.split(' ')
    
    datas = []
    for i in data:
        i = re.sub(',', '', i)
        datas.append(i)
        
    df_const.loc[j] = datas[-data_len:]

driver.close()

df_const

,2019 1/4,2019 2/4,2019 3/4,2019 4/4,2020 1/4,2020 2/4,2020 3/4,2020 4/4,2021 1/4,2021 2/4,2021 3/4,2021 4/4
총계,26147,31280,23764,28478,26373,32190,30319,34815,31077,35547,31184,37489
전년대비증감율,-12.0,19.6,-24.0,19.8,-7.4,22.1,-5.8,14.8,-10.7,14.4,-12.3,20.2
주거용,7993,10634,6903,7827,6953,10783,10357,12166,11332,11025,11052,13372
상업용,7330,7988,6075,7091,7329,8870,7098,8585,7069,11030,9168,9822
농수산용,3243,3459,3641,4211,3080,3036,2294,2513,2009,2161,1448,1485
공업용,3374,4159,3630,3770,3242,3291,4126,4522,3529,4590,3248,4611
공공용,175,144,134,131,131,60,202,130,238,172,173,218
교육사회용,1332,1381,1368,1704,1580,2001,1421,1925,1520,2162,1535,2318
기타,2697,3512,2010,3741,4055,4145,4819,4971,5377,4403,4559,5661

#### # MariaDB에 데이터 입력
---

In [ ]:
df_const_sql = df_const.T.reset_index()
df_const_sql['단위'] = '천m²'
df_const_sql['연도'] = [int(year[:4]) for year in df_const_sql['index']]
df_const_sql['분기'] = [int(month[4:6]) for month in df_const_sql['index']]
df_const_sql = df_const_sql[['연도', '분기', '총계', '전년대비증감율', '주거용', '상업용', '농수산용', '공업용', '공공용', '교육사회용', '기타', '단위']]
df_const_sql.iloc[:, 2:len(df_const_sql.columns)-1] = df_const_sql.iloc[:, 2:len(df_const_sql.columns)-1].astype('float64')

df_const_sql

db_connection_str = 'mysql+pymysql://root:root@127.0.0.1:3306/smart_factory'
db_connection = create_engine(db_connection_str)
conn = db_connection.connect()

# df_per_sql.to_sql(name = 'building_permission',con = db_connection, index = False)
df_const_sql.to_sql(name = 'building_construction',con = db_connection, index = False, if_exists = 'replace') # 테이블 삭제하고 새로 만들 때 사용
# df_per_sql.to_sql(name = 'building_permission',con = db_connection, index = False, if_exists = 'append') # 데이터를 추가할 때 사용