In [ ]:
# pd.set_option('display.max_column', 3)
# pd.set_option('display.width', 5)

In [1]:
import pandas as pd

In [2]:
# pd.set_option('display.max_colwidth',50)

In [3]:
# pd.describe_option()

In [52]:
import pandas as pd
import glob
import os
import numpy as np
path = r'H:\내 드라이브\cakd5\workspace\m8_머신러닝응용\dataset\OpinosisDataset1.0\topics'

all_files = glob.glob(os.path.join(path, "*.data"))
filename_list = []
opinion_text = []

for file_ in all_files:
    df = pd.read_table(file_, index_col=None, header=0, encoding='latin1')
    filename_ = file_.split('\\')[-1]
    filename = filename_.split('.')[0]

    filename_list.append(filename)
    opinion_text.append(df.to_string())

document_df = pd.DataFrame(
    {'filename': filename_list, 'opinion_text': opinion_text})

document_df = document_df.sort_values('filename')

document_df.index = np.arange(0, 51)
document_df.head()

,filename,opinion_text
0,accuracy_garmin_nuvi_255W_gps,...
1,bathroom_bestwestern_hotel_sfo,...
2,battery-life_amazon_kindle,...
3,battery-life_ipod_nano_8gb,...
4,battery-life_netbook_1005ha,...

In [46]:
from nltk.stem import WordNetLemmatizer
import nltk
import string

remove_punct_dict = dict((ord(punct), None)for punct in string.punctuation)
lemma = WordNetLemmatizer()

def LemTokens(tokens):
    return [lemma.lemmatize(token) for token in tokens]

def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english', ngram_range=(
    1, 2), min_df=0.05, max_df=0.85)
feature_vect = tfidf_vect.fit_transform(document_df['opinion_text'])

D:\anaconda3\envs\cakd5\lib\site-packages\sklearn\feature_extraction\text.py:396: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  warnings.warn(

In [48]:
from sklearn.cluster import KMeans

km_cluster = KMeans(n_clusters=5, max_iter=10000, random_state=0)
km_cluster.fit(feature_vect)
cluster_label = km_cluster.labels_
clister_centers = km_cluster.cluster_centers_

In [49]:
document_df['cluster_label'] = cluster_label
document_df.head()

,filename,opinion_text,cluster_label
0,accuracy_garmin_nuvi_255W_gps,...,2
1,bathroom_bestwestern_hotel_sfo,...,0
2,battery-life_amazon_kindle,...,1
3,battery-life_ipod_nano_8gb,...,1
4,battery-life_netbook_1005ha,...,1

In [44]:
#정렬전 클러스트
document_df.cluster_label.value_counts()

4    18
3    12
2    10
1     7
0     4
Name: cluster_label, dtype: int64

In [50]:
#정렬후 클러스트
document_df.cluster_label.value_counts()

2    16
3    13
4    10
1     8
0     4
Name: cluster_label, dtype: int64

In [9]:
from sklearn.cluster import KMeans

km_cluster = KMeans(n_clusters=3, max_iter=10000, random_state=0)
km_cluster.fit(feature_vect)
cluster_label = km_cluster.labels_
clister_centers = km_cluster.cluster_centers_
document_df['cluster_label'] = cluster_label

In [10]:
document_df[document_df.cluster_label == 0].sort_values('filename')  # 전자기기

,filename,opinion_text,cluster_label
0,accuracy_garmin_nuvi_255W_gps,...,0
2,battery-life_amazon_kindle,...,0
3,battery-life_ipod_nano_8gb,...,0
4,battery-life_netbook_1005ha,...,0
5,buttons_amazon_kindle,...,0
8,directions_garmin_nuvi_255W_gps,...,0
9,display_garmin_nuvi_255W_gps,...,0
10,eyesight-issues_amazon_kindle,...,0
11,features_windows7,...,0
12,fonts_amazon_kindle,...,0
19,keyboard_netbook_1005ha,...,0
23,navigation_amazon_kindle,...,0
26,performance_netbook_1005ha,...,0
27,price_amazon_kindle,...,0
33,satellite_garmin_nuvi_255W_gps,...,0
34,screen_garmin_nuvi_255W_gps,...,0
35,screen_ipod_nano_8gb,...,0
36,screen_netbook_1005ha,...,0
41,size_asus_netbook_1005ha,...,0
42,sound_ipod_nano_8gb,headphone jack i got a clear case for it a...,0
43,speed_garmin_nuvi_255W_gps,...,0
44,speed_windows7,...,0
48,updates_garmin_nuvi_255W_gps,...,0
49,video_ipod_nano_8gb,...,0
50,voice_garmin_nuvi_255W_gps,...,0

In [11]:
document_df[document_df.cluster_label == 1].sort_values('filename')  # 자동차

,filename,opinion_text,cluster_label
6,comfort_honda_accord_2008,...,1
7,comfort_toyota_camry_2007,...,1
16,gas_mileage_toyota_camry_2007,...,1
17,interior_honda_accord_2008,...,1
18,interior_toyota_camry_2007,...,1
22,mileage_honda_accord_2008,...,1
25,performance_honda_accord_2008,...,1
29,quality_toyota_camry_2007,...,1
37,seats_honda_accord_2008,...,1
47,transmission_toyota_camry_2007,...,1

In [12]:
document_df[document_df.cluster_label == 2].sort_values('filename')  # 호텔

,filename,opinion_text,cluster_label
1,bathroom_bestwestern_hotel_sfo,...,2
13,food_holiday_inn_london,...,2
14,food_swissotel_chicago,...,2
15,free_bestwestern_hotel_sfo,...,2
20,location_bestwestern_hotel_sfo,...,2
21,location_holiday_inn_london,...,2
24,parking_bestwestern_hotel_sfo,...,2
28,price_holiday_inn_london,...,2
30,room_holiday_inn_london,...,2
31,rooms_bestwestern_hotel_sfo,...,2
32,rooms_swissotel_chicago,...,2
38,service_bestwestern_hotel_sfo,...,2
39,service_holiday_inn_london,...,2
40,service_swissotel_hotel_chicago,...,2
45,staff_bestwestern_hotel_sfo,...,2
46,staff_swissotel_chicago,...,2

# 군집별 핵심 단어 추출

In [13]:
cluster_centers = km_cluster.cluster_centers_

print('cluster_centers shape :', cluster_centers.shape)
print(cluster_centers)

cluster_centers shape : (3, 4611)
[[0.01005322 0.         0.         ... 0.00706287 0.         0.        ]
 [0.         0.00092551 0.         ... 0.         0.         0.        ]
 [0.         0.00099499 0.00174637 ... 0.         0.00183397 0.00144581]]

In [14]:
def get_cluster_details(cluster_model, cluster_data, cluster_nums,
                        feature_names, top_n_features=10):
    cluster_details = {}

    center_info = cluster_model.cluster_centers_
    center_descend_ind = center_info.argsort()[:, ::-1]
    #내림차순
    for i in range(cluster_nums):

        cluster_details[i] = {}

        filenames = cluster_data[cluster_data["cluster_label"]
                                 == i]["filename"]
        filenames = filenames.values.tolist()

        top_feature_values = center_info[i, :top_n_features].tolist()

        top_feature_indexes = center_descend_ind[i, :top_n_features]
        top_features = [feature_names[ind] for ind in top_feature_indexes]

        cluster_details[i]["cluster"] = i
        cluster_details[i]["top_features"] = top_features
        cluster_details[i]["top_feature_values"] = top_feature_values
        cluster_details[i]["filenames"] = filenames

    return cluster_details

In [15]:
feature_names = tfidf_vect.get_feature_names()

cluster_details = get_cluster_details(cluster_model=km_cluster, cluster_data=document_df, cluster_nums=3,
                                      feature_names=feature_names, top_n_features=10)

D:\anaconda3\envs\cakd5\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [16]:
cluster_details.keys()

dict_keys([0, 1, 2])

In [17]:
cluster_details[0]

{'cluster': 0,
 'top_features': ['screen',
  'battery',
  'keyboard',
  'battery life',
  'life',
  'kindle',
  'direction',
  'video',
  'size',
  'voice'],
 'top_feature_values': [0.010053218166968707,
  0.0,
  0.0,
  0.0012728840547508097,
  0.0,
  0.0,
  0.0005287118570479554,
  0.0,
  0.0010331093719477017,
  0.0],
 'filenames': ['accuracy_garmin_nuvi_255W_gps',
  'battery-life_amazon_kindle',
  'battery-life_ipod_nano_8gb',
  'battery-life_netbook_1005ha',
  'buttons_amazon_kindle',
  'directions_garmin_nuvi_255W_gps',
  'display_garmin_nuvi_255W_gps',
  'eyesight-issues_amazon_kindle',
  'features_windows7',
  'fonts_amazon_kindle',
  'keyboard_netbook_1005ha',
  'navigation_amazon_kindle',
  'performance_netbook_1005ha',
  'price_amazon_kindle',
  'satellite_garmin_nuvi_255W_gps',
  'screen_garmin_nuvi_255W_gps',
  'screen_ipod_nano_8gb',
  'screen_netbook_1005ha',
  'size_asus_netbook_1005ha',
  'sound_ipod_nano_8gb',
  'speed_garmin_nuvi_255W_gps',
  'speed_windows7',
  'updates_garmin_nuvi_255W_gps',
  'video_ipod_nano_8gb',
  'voice_garmin_nuvi_255W_gps']}

In [18]:
cluster_details[1]

{'cluster': 1,
 'top_features': ['interior',
  'seat',
  'mileage',
  'comfortable',
  'gas',
  'gas mileage',
  'transmission',
  'car',
  'performance',
  'quality'],
 'top_feature_values': [0.0,
  0.0009255147372799377,
  0.0,
  0.0008702067130558922,
  0.0032590969178663727,
  0.001545126725807888,
  0.004201757376739963,
  0.006807581988201698,
  0.003832611518738106,
  0.0],
 'filenames': ['comfort_honda_accord_2008',
  'comfort_toyota_camry_2007',
  'gas_mileage_toyota_camry_2007',
  'interior_honda_accord_2008',
  'interior_toyota_camry_2007',
  'mileage_honda_accord_2008',
  'performance_honda_accord_2008',
  'quality_toyota_camry_2007',
  'seats_honda_accord_2008',
  'transmission_toyota_camry_2007']}

In [19]:
cluster_details[2]

{'cluster': 2,
 'top_features': ['room',
  'hotel',
  'service',
  'staff',
  'food',
  'location',
  'bathroom',
  'clean',
  'price',
  'parking'],
 'top_feature_values': [0.0,
  0.0009949872709281234,
  0.0017463747128866542,
  0.004164229995258945,
  0.0,
  0.0001683620146360523,
  0.0,
  0.0,
  0.00234423377643847,
  0.002360101992468045],
 'filenames': ['bathroom_bestwestern_hotel_sfo',
  'food_holiday_inn_london',
  'food_swissotel_chicago',
  'free_bestwestern_hotel_sfo',
  'location_bestwestern_hotel_sfo',
  'location_holiday_inn_london',
  'parking_bestwestern_hotel_sfo',
  'price_holiday_inn_london',
  'room_holiday_inn_london',
  'rooms_bestwestern_hotel_sfo',
  'rooms_swissotel_chicago',
  'service_bestwestern_hotel_sfo',
  'service_holiday_inn_london',
  'service_swissotel_hotel_chicago',
  'staff_bestwestern_hotel_sfo',
  'staff_swissotel_chicago']}

In [22]:
for cluster_num, cluster_detail in cluster_details.items():
    print(f"Cluster {cluster_num}")
    print(f"Top features: {cluster_detail['top_features']}")
    print(f"Reviews 파일명: {cluster_detail['filenames'][:3]}")
    print("\n")

Cluster 0
Top features: ['screen', 'battery', 'keyboard', 'battery life', 'life', 'kindle', 'direction', 'video', 'size', 'voice']
Reviews 파일명: ['accuracy_garmin_nuvi_255W_gps', 'battery-life_amazon_kindle', 'battery-life_ipod_nano_8gb', 'battery-life_netbook_1005ha', 'buttons_amazon_kindle', 'directions_garmin_nuvi_255W_gps', 'display_garmin_nuvi_255W_gps', 'eyesight-issues_amazon_kindle', 'features_windows7', 'fonts_amazon_kindle', 'keyboard_netbook_1005ha', 'navigation_amazon_kindle', 'performance_netbook_1005ha', 'price_amazon_kindle', 'satellite_garmin_nuvi_255W_gps', 'screen_garmin_nuvi_255W_gps', 'screen_ipod_nano_8gb', 'screen_netbook_1005ha', 'size_asus_netbook_1005ha', 'sound_ipod_nano_8gb', 'speed_garmin_nuvi_255W_gps', 'speed_windows7', 'updates_garmin_nuvi_255W_gps', 'video_ipod_nano_8gb', 'voice_garmin_nuvi_255W_gps']


Cluster 1
Top features: ['interior', 'seat', 'mileage', 'comfortable', 'gas', 'gas mileage', 'transmission', 'car', 'performance', 'quality']
Reviews 파일명: ['comfort_honda_accord_2008', 'comfort_toyota_camry_2007', 'gas_mileage_toyota_camry_2007', 'interior_honda_accord_2008', 'interior_toyota_camry_2007', 'mileage_honda_accord_2008', 'performance_honda_accord_2008', 'quality_toyota_camry_2007', 'seats_honda_accord_2008', 'transmission_toyota_camry_2007']


Cluster 2
Top features: ['room', 'hotel', 'service', 'staff', 'food', 'location', 'bathroom', 'clean', 'price', 'parking']
Reviews 파일명: ['bathroom_bestwestern_hotel_sfo', 'food_holiday_inn_london', 'food_swissotel_chicago', 'free_bestwestern_hotel_sfo', 'location_bestwestern_hotel_sfo', 'location_holiday_inn_london', 'parking_bestwestern_hotel_sfo', 'price_holiday_inn_london', 'room_holiday_inn_london', 'rooms_bestwestern_hotel_sfo', 'rooms_swissotel_chicago', 'service_bestwestern_hotel_sfo', 'service_holiday_inn_london', 'service_swissotel_hotel_chicago', 'staff_bestwestern_hotel_sfo', 'staff_swissotel_chicago']